import QCLib.Mathlib.Lemmas
import QCLib.Mathlib.LinearAlgebra.PiOuterProduct
import QCLib.Mathlib.LinearAlgebra.UnitaryGroup.PiKronecker
import QCLib.Mathlib.LinearAlgebra.UnitaryGroup.Lemmas
import QCLib.Matrix.Action
import QCLib.Matrix.UnitaryGroup.Action
import QCLib.Matrix.UnitaryGroup.Basic
import QCLib.Matrix.UnitaryGroup.Kronecker
import QCLib.Matrix.UnitaryGroup.RootsOfUnity
import QCLib.Matrix.UnitaryGroup.DiagonalSubgroup
import QCLib.Circuit.StdBasis
import QCLib.Circuit.Qubit
import QCLib.Circuit.Hadamard
import QCLib.Circuit.PauliGenerators
import QCLib.Circuit.PauliGroup
import QCLib.Misc.OrderOf
import QCLib.Misc.IntCast
import QCLib.Tactic.MatrixExpand
