/-
Copyright (c) 2026 David Gross. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Gross
-/
module

public import Mathlib

/-!

*Broke with https://github.com/leanprover-community/mathlib4/pull/36549*

[Working version in old repos]

Express a `noncommProd` of factors in a `Monoid M` as an ordinary product in a
`CommMonoid S` that is a `Submonoid M` and contains all the factors.

## Main defintions

* `Submonoid.isMulComm_of_commute`: An `IsMulCommutative` reducible non-instance on the closure of
  pairwise commuting elements

## Main results

* `Multiset.noncommProd_eq_prod_of_comm_submonoid`: The `noncommProd` can be taken in any
  `Submonoid S` that satisfies `IsMulCommutative S` and contains all the factors.

* `Multiset.noncommProd_eq_prod'`: The above, specialized to `S` being the `Monoid` generated by
  the factors.

* `Finset.noncommProd_eq_prod_of_comm_submonoid`: The `noncommProd` can be taken in any
  `Submonoid S` that satisfies `IsMulCommutative S` and contains all the factors.

* `Finset.noncommProd_eq_prod'`: The above, specialized to `S` being the `Monoid` generated by
  the factors.

## Implementation notes

The definitions can't assume `(S : Submonoid M) [CommMonoid S]`, because both
arguments come with their own `Mul` instance. To avoid incompatible `Mul`s, we
need a `Prop`-valued typeclass that expresses that multiplication is
commutative. Two such classes are provided:

* `Std.Commmutative (α := S) (· * ·)`, and
* `IsMulCommutative`, which is just a wrapper around the previous one.

Mathlib declares intances for these conversions:
```
(1) CommMonoid -> CommMagma -> Std.Commutative

(2)                            IsMulCommutative -> CommMonoid
```

In a definition that assumes `(S : Submonoid M) [IsMulCommutative S]`, Lean can
use (2) to synthesize `CommMonoid S` with a `Mul` instance that is defeq to the
one of `M`.

To use such definitions, we need to register `IsMulCommutative` instances for
the submonoids of interest.

Here, one needs to be careful in order not to create performance issues:

`CommMonoid` is a very common assumption, and every time it appears in a
typeclass search, each `IsMulCommutative` instance will have to be considered.
Therefore, `IsMulCommutative` instances must be very specific, so that they can
be quickly discarded when they do not apply.

Indeed, `egrep -R "IsMulCommutative.*instance" Mathlib` finds only a small
number of very specific instances, and the docstring of `CommGroup` explicitly
mentions that there is no `IsMulCommutative` instance "for performance reasons".
In particular, an instance `Std.Commutative -> IsMulCommutative` would tank
performance (that was our initial attempt).

## To be done

* Missing API for `Pairwise`? Is there an `_iff` lemma?
-/

@[expose] public section

/- Misc lemmas. Put somewhere appropriate.  -/
section Lemmas

@[simp]
theorem Submonoid.coe_commute_iff {M : Type*} [Monoid M] {S : Submonoid M} {a b : S} :
    (Commute (a : M) (b : M)) ↔ Commute a b := by
  refine ⟨(fun h ↦ ?_), (fun h ↦ ?_)⟩
  · simpa [commute_iff_eq, S.mul_def]
  · simpa [commute_iff_eq] using congrArg S.subtype h.eq

end Lemmas

#check CommSemigroup

/- Start with some results that are independent of the main body of this file. -/
section Independent

variable {F ι α β γ : Type*} (f : α → β)

open Finset

variable [Monoid β] [Monoid γ]

open scoped Function

/-- Write a `noncommProd` that factors through a commutative monoid as an ordinary product. -/
theorem noncommProd_comp_eq_prod {α β γ F : Type*} [Monoid α] [CommMonoid β] [Monoid γ]
    [FunLike F β γ] [MonoidHomClass F β γ] (s : Finset α) (f : α → β) (g : F) :
    s.noncommProd (g ∘ f) (fun x _ y _ _ ↦ (Commute.all (f x) (f y)).map g) = g (s.prod f) := by
  simp [← map_noncommProd s f fun x _ y _ _ ↦ Commute.all (f x) (f y), noncommProd_eq_prod]


theorem noncommProd_lemma' (s : Finset α) (f : α → β) (comm : (s : Set α).Pairwise (Commute on f)) :
    Set.Pairwise {x | x ∈ s.toList.map f} Commute := by
  have h : { x | x ∈ s.val.map f } = {x | x ∈ s.toList.map f}  := by simp
  exact h ▸ noncommProd_lemma s f comm

@[simp, grind =]
theorem noncommprod_map_toList (s : Finset α) (comm) :
    (s.toList.map f).prod = s.noncommProd f comm := by
  simp only [Finset.noncommProd, ← Multiset.noncommProd_coe _ <| noncommProd_lemma' s f comm,
    ← Multiset.map_coe, Finset.coe_toList]

end Independent

namespace Multiset

variable {M : Type*} [Monoid M] {S : Multiset M}

/-- If the elements of a multiset in a monoid are all contained in a commutative
submonoid, then they commute pairwise. -/
theorem pairwise_comm_of_submonoid {N : Submonoid M} [IsMulCommutative N]
    (hsub : { x | x ∈ S } ⊆ N) : { x | x ∈ S }.Pairwise Commute :=
    fun x hx y hy _ ↦ Submonoid.coe_commute_iff.mpr <|
      Commute.all (Set.inclusion hsub ⟨x, hx⟩) (Set.inclusion hsub ⟨y, hy⟩)

#check CommMonoid.ofIsMulCommutative.toCommSemigroup.toCommMagma

/-- Cast `S : Multiset M` to `Multiset N`, assuming all elements of `S` are contained in `N`.

This exists mostly for the type ascription `Multiset N`. Without it, the eleborator tends to
interpret the type of `S.attach.map (Set.inclusion hsub)` as `Multiset {x // x ∈ N}`. -/
@[simp]
abbrev castOfSubset {T : Type*} [SetLike T M] {N : T} (hsub : { x | x ∈ S } ⊆ N) : Multiset N :=
    S.attach.map (Set.inclusion hsub)

/-- The noncommutative product of terms that are contained in a commutative
submonoid equals their product taken in the submonoid. -/
theorem noncommProd_eq_prod_of_comm_submonoid
    {N : Submonoid M} [hcomm : IsMulCommutative N] (hsub : { x | x ∈ S } ⊆ N) :
    noncommProd S (pairwise_comm_of_submonoid hsub) = (castOfSubset hsub).prod := by
  induction S using Quotient.inductionOn
  simp

open Submonoid

/-- An `IsMulCommutative` reducible non-instance on the closure of pairwise commuting elements -/
abbrev _root_.Submonoid.isMulCommutative_of_commute {S : Set M} (comm : S.Pairwise Commute) :
    IsMulCommutative (closure S) where
  is_comm := .mk fun x y ↦ by
    obtain ⟨x, hx⟩ := x
    obtain ⟨y, hy⟩ := y
    induction hx, hy using closure_induction₂ with
    | mem x y hx hy => simp [(comm.of_refl hx hy).eq]
    | one_left x hx => simp
    | one_right y hy => simp
    | mul_left x y z hx hy hz hil hir =>
      simp only [mk_mul_mk] at *
      grind
    | mul_right x y z hx hy z =>
      simp only [mk_mul_mk] at *
      grind

/-- Embeds a `Multiset` on a monoid into its closure.

This exists mostly for the type ascription. -/
@[simp]
abbrev inclusionClosure (S : Multiset M) : Multiset (Submonoid.closure { x | x ∈ S }) :=
  S.attach.map (Set.inclusion Submonoid.subset_closure)

/-- Express the non-commutative product as an ordinary product in the commutative
monoid generated by the factors -/
theorem noncommProd_eq_prod' (S : Multiset M) (comm : { x | x ∈ S}.Pairwise Commute) :
    letI := isMulCommutative_of_commute comm
    S.noncommProd comm = S.inclusionClosure.prod :=
    noncommProd_eq_prod_of_comm_submonoid (hcomm := _) subset_closure

end Multiset

namespace Finset

open scoped Function

variable {M : Type*} [Monoid M]
variable {ι : Type*} {S : Finset ι} (f : ι → M)

theorem pairwise_comm_of_submonoid {N : Submonoid M} [IsMulCommutative N]
  (hsub : ∀ x ∈ S, f x ∈ N) : { x | x ∈ S }.Pairwise (Commute on f) :=
    fun x hx y hy _ ↦ Submonoid.coe_commute_iff.mpr <|
      Commute.all (Subtype.map f hsub ⟨x, hx⟩) (Subtype.map f hsub ⟨y, hy⟩)

theorem noncommProd_eq_prod_of_comm_submonoid
    {N : Submonoid M} [hcomm : IsMulCommutative N] (hsub : ∀ i ∈ S, f i ∈ N) :
    S.noncommProd f (pairwise_comm_of_submonoid f hsub) = S.attach.prod (Subtype.map f hsub) := by
  induction S using Finset.cons_induction_on <;> simp_all [Subtype.map_def]

open Submonoid

/-- Given `S : Finset ι` and a function `f : ι → M` with `M` a `Monoid`,
return a function from `S` to the closure of the image of `S` under `f`. -/
def _root_.Function.liftFunToClosure (a : S) : Submonoid.closure { x | x ∈ S.val.map f } :=
    ⟨f a, mem_closure_of_mem (by aesop)⟩

theorem _root_.Function.liftFunToClosure_apply (a : S) :
    Function.liftFunToClosure f a = ⟨f a, mem_closure_of_mem (by aesop)⟩ := rfl

theorem noncommProd_eq_prod' (comm : (S : Set ι).Pairwise (Commute on f)) :
    letI := isMulCommutative_of_commute (S.noncommProd_lemma f comm)
    (S.noncommProd f comm) = S.attach.prod f.liftFunToClosure :=
  noncommProd_eq_prod_of_comm_submonoid (hcomm := _) f (by aesop)

end Finset

section Tests

-- Make more general? Performance?
instance {G : Type*} [Group G] (H : Subgroup G) [IsMulCommutative H] :
    IsMulCommutative H.toSubmonoid where is_comm := ⟨mul_comm⟩

variable {n : Type*} [Fintype n] [DecidableEq n] {R : Type*} [CommRing R] [StarRing R]

open Matrix Matrix.UnitaryGroup

instance : IsMulCommutative (diagonalSubgroup n R) where is_comm := ⟨mul_comm⟩

open Multiset in
example {S : Multiset (unitaryGroup n R)} (hsub : { x | x ∈ S } ⊆ diagonalSubgroup n R) :
    S.noncommProd (pairwise_comm_of_submonoid hsub) = (castOfSubset hsub).prod :=
    noncommProd_eq_prod_of_comm_submonoid hsub

-- could make `f` implicit
open Finset in
example {ι : Type*} {S : Finset ι} (f : ι → unitaryGroup n R)
    (hsub : ∀ x ∈ S, f x ∈ diagonalSubgroup n R) :
    S.noncommProd f (pairwise_comm_of_submonoid f hsub) = S.attach.prod (Subtype.map f hsub) :=
    noncommProd_eq_prod_of_comm_submonoid f hsub

end Tests

section ConvertProofs


end ConvertProofs

/- These ended up not being required -/
section NotUsed

variable {M : Type*} [Monoid M]

open Submonoid

open scoped Function -- required for scoped `on` notation

--- TBD: Is there an analogous `prod` statement? Get names aligned.
@[simp, norm_cast]
theorem _root_.Submonoid.coe_noncommProd (N : Submonoid M) (s : Finset ι) (f : ι → N)
    (comm : (s : Set ι).Pairwise (Commute on f)) :
    (↑(s.noncommProd f comm) : M) = s.noncommProd (fun i ↦ ↑(f i))
      (comm.imp (fun _ _ h ↦ coe_commute_iff.mpr h)) :=
  s.map_noncommProd f comm N.subtype

namespace Finset

/-- Analogue of `Finset.prod_attach`. -/
theorem noncommProd_attach {ι : Type*} (S : Finset ι) (f : ι → M)
    (comm : (S : Set ι).Pairwise (Commute on f)) :
    (S.noncommProd f comm) = S.attach.noncommProd (fun x ↦ f x)
    ((fun ⟨_, ha⟩ _ ⟨_, hb⟩ _ hne ↦ comm ha hb (fun h ↦ hne (Subtype.ext h)))) := by
  simp only [noncommProd, attach_val]
  congr 1
  rw [← Multiset.attach_map_val']
  rfl -- TBD

end NotUsed.Finset
