/-
Copyright (c) 2026 David Gross. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: David Gross
-/
import Mathlib

/-!

# Representation of elements of `ZMod (d ^ n)` by digits

This WIP file builds a theory of "digits" for elements of `ℤ_{d^n}`.

The module is motivated by the observation that the structure of the quantum
Fourier transform circuit reflects a certain recursive formula for multiplying
numbers in `ℤ_{d^n}` in terms of their digits.

## Main definitions

* `digitsEquiv : ZMod (d ^ n) ≃ (Fin n → Fin d)` represents `ZMod d ^ n` by digits,
in little-endian order

* `digitsBEEquiv : ZMod (d ^ n) ≃ (Fin n → Fin d)` represents `ZMod d ^ n` by digits,
in big-endian order


## Main results

* `ofDigits_mul_ofDigitsBE_rec` a recursive formula for multiplying numbers in
`ZMod d ^ n`, where one is given in BE and one in LE order.

* `idftRec` a recursive formula for the inverse DFT over `ℤ_{d^n}`

## To do

Clean up this mess.

-/

section lemmas

@[simp]
theorem ZMod.val_sum_of_lt {ι : Type*} {n : ℕ} (f : ι → ZMod n) (s : Finset ι)
    (h : ∑ i ∈ s, (f i).val < n) : (∑ i ∈ s, f i).val = ∑ i ∈ s, (f i).val := by
  have : NeZero n := by constructor; rintro rfl; simp at h
  induction s using Finset.cons_induction with
  | empty => simp
  | cons a s ha hi => simp_all [val_add_of_lt, hi (by grind)]

-- Is this an idiomatic statement?
@[to_additive]
theorem Finset.prod_univ_split {M : Type*} [CommMonoid M] {n : ℕ} (j : Fin n) (f : Fin n → M) :
    (∏ i, f i) = (∏ i ≤ j, f i) * ∏ i > j, f i := by
  have hu : Finset.univ = (Finset.Iic j) ∪ (Finset.Ioi j) := by grind
  have hd : Disjoint (Finset.Iic j) (Finset.Ioi j) := by grind [Finset.disjoint_left]
  rw [hu, Finset.prod_union hd]

end lemmas

namespace Nat

-- not used
theorem ofDigits_expand {p : ℕ} (L : List ℕ) :
    ofDigits p L = ∑ i : Fin L.length, L[i] * p ^ (i : ℕ) := by
  induction L with
  | nil => simp
  | cons h t hi =>
    simp [Fin.sum_univ_succ, ofDigits_cons, hi, Finset.mul_sum]
    ring_nf

attribute [simp] Nat.pos_of_neZero
attribute [simp] Nat.AtLeastTwo.one_lt

end Nat

namespace Fin

abbrev digitsEquiv {n d : ℕ} : Fin (d ^ n) ≃ (Fin n → Fin d) := finFunctionFinEquiv.symm

-- Re-uses a proof from `finFunctionFinEquiv`.
@[simp]
theorem ofDigits_lt {m n : ℕ} (f : Fin n → Fin m) :
    ∑ i, f i * m ^ (i : ℕ) < m ^ n :=
  (digitsEquiv.symm f).isLt

-- `NeZero m` not necessary
@[simp]
theorem ofDigits_lt' {m n k : ℕ} [NeZero m] (hkn : k ≤ n) (f : Fin k → Fin m) :
    ∑ i, f i * m ^ (i : ℕ) < m ^ n := by
  refine lt_of_lt_of_le (ofDigits_lt f) ?_
  exact Nat.pow_le_pow_right (by simp) hkn

-- That's different from `_root_.finFunctionFinEquiv` (which is also a dupe of
-- the one generated by `simps`. TBD: PR to deprecate)
theorem finFunctionFinEquiv_apply {m n : ℕ} (f : Fin n → Fin m) :
    digitsEquiv.symm f = ⟨∑ i, f i * m ^ (i : ℕ), ofDigits_lt f⟩ := by
  ext; simp

theorem val_self_expansion {n d : ℕ} (x : Fin (d ^ n)) :
    (x : ℕ) = ∑ i, (finFunctionFinEquiv.symm x i) * (d ^ (i : ℕ) : ℕ) := by
  conv_lhs => rw [show x = finFunctionFinEquiv (finFunctionFinEquiv.symm x) by simp]
  simp only [finFunctionFinEquiv_apply_val]

end Fin

namespace ZMod

section castHom

@[simp]
theorem pow_div_pow {d e n : ℕ} : d ^ n ∣ d ^ (n + e) := by
  simp [pow_add]

@[simp]
theorem pow_div_pow_succ {d n : ℕ} : d ^ n ∣ d ^ n.succ := pow_div_pow (e:=1)

@[simps!]
def castHomPow (d n e : ℕ) : ZMod (d ^ (n + e)) →+* ZMod (d ^ n) :=
  castHom pow_div_pow (ZMod (d ^ n))

@[simps!]
def predHom (d n : ℕ) : ZMod (d ^ (n + 1)) →+* ZMod (d ^ n) :=
  castHom pow_div_pow_succ (ZMod (d ^ n))

variable {d n e : ℕ}

@[simp]
theorem predHom_ker' : predHom d n (d ^ n) = 0 := by
  simp [natCast_pow_eq_zero_of_le]

theorem castHomePow_ker (x : Fin e → (ZMod (d ^ (n + e)))) :
    castHomPow d n e (∑ i, x i * ↑d ^ (n + i)) = 0 := by
  simp [natCast_pow_eq_zero_of_le]

end castHom

-- Some pieces of missing API for `ZMod.finEquiv`
section finEquiv

@[simp]
theorem finEquiv_val {n : ℕ} [hnz : NeZero n] (x : Fin n) : (finEquiv n x).val = (x : ℕ) := by
  cases n
  · cases NeZero.ne 0 rfl
  · rfl

@[simp]
theorem finEquiv_symm_val {n : ℕ} [NeZero n] (x : ZMod n) : ((finEquiv n).symm x).val = x.val := by
  cases n
  · cases NeZero.ne 0 rfl
  · rfl

@[simp]
theorem finEquiv_symm_cast_val {n : ℕ} [NeZero n] (x : Fin n) :
    (finEquiv n).symm (x.val : ZMod n) = x := by
  ext
  simp only [finEquiv_symm_val, val_natCast_of_lt x.isLt]

end finEquiv

-- namespace to allow for dot notation
def _root_.Function.ofDigits {n d : ℕ} (f : Fin n → Fin d) : (ZMod (d ^ n)) :=
  ((Fin.digitsEquiv.symm f) : ZMod (d ^ n))

theorem ofDigits_def {n d : ℕ} (f : Fin n → Fin d) :
    f.ofDigits = ((Fin.digitsEquiv.symm f) : ZMod (d ^ n)) := rfl

def digits {n d : ℕ} [NeZero d] (x : ZMod (d ^ n)) : Fin n → Fin d :=
  fun i ↦ finFunctionFinEquiv.symm ((ZMod.finEquiv _).symm x) i

theorem digits_def {n d : ℕ} [NeZero d] (x : ZMod (d ^ n)) :
    x.digits = Fin.digitsEquiv ((finEquiv (d ^ n)).symm x) := rfl

theorem digits_ofDigits {n d : ℕ} [NeZero d] (f : Fin n → Fin d) :
    digits f.ofDigits = f := by
  ext i
  simp only [digits_def, ofDigits_def, finEquiv_symm_cast_val, Equiv.symm_symm,
    Equiv.symm_apply_apply]

theorem ofDigits_digits {n d : ℕ} [NeZero d] (x : ZMod (d ^ n)) :
    x.digits.ofDigits = x := by
  simp [digits_def, ofDigits_def]

-- TBD: Make `apply_val` non-simp?
@[simps!?]
def digitsEquiv {n d : ℕ} [NeZero d] : (ZMod (d ^ n)) ≃ (Fin n → Fin d) where
  toFun := digits
  invFun := Function.ofDigits
  left_inv := ofDigits_digits
  right_inv := digits_ofDigits
-- or use this as standard lemmas?
theorem digitsEquiv_apply {n d : ℕ} [NeZero d] (x : ZMod (d ^ n)) : digitsEquiv x = x.digits := rfl

-- collect trivial stuff now, reduce later
section trivialities

-- Easier?
@[simp]
theorem _root_.Nat.le_pow_pow_add {n d e : ℕ} [NeZero d] : d ^ n ≤ d ^ (n + e) :=
  Nat.pow_le_pow_right (gt_iff_lt.mpr (by simp)) (by simp)

@[simp]
theorem _root_.Fin.le_pow_pow_self {n d : ℕ} [NeZero d] (i : Fin n) : d ^ (i : ℕ) ≤ d ^ n :=
  Nat.pow_le_pow_right (by simp) (by simp)

@[simp]
theorem _root_.Fin.lt_pow_pow_self {n m d : ℕ} [d.AtLeastTwo] (hmn : m ≤ n) (i : Fin m) :
  d ^ (i : ℕ) < d ^ n :=
  Nat.pow_lt_pow_right (by simp) (by grind)

theorem val_cast_succ_eq_val {n d : ℕ} [NeZero d] (a : ZMod (d ^ n)) :
    (a.cast : ZMod (d ^ (n + 1))).val = a.val :=
  val_cast_eq_val_of_lt <| lt_of_lt_of_le a.val_lt (by simp)

theorem cast_succ_cast {n d : ℕ} [NeZero d] (a : ZMod (d ^ n)) :
    (a.cast : ZMod (d ^ (n + 1))).cast = a :=
  cast_cast_zmod_of_le (by simp) a

/-- Analogue of `ZMod.val_cast_eq_va_of_lt` starting from a `Fin` -/
theorem _root_.Fin.val_zModCast_of_le {n m : ℕ} [NeZero n] (h : n ≤ m) (a : Fin n) :
    (a.val : ZMod m).val = a := by
  rw [val_natCast]
  exact Nat.mod_eq_of_lt <| lt_of_lt_of_le a.is_lt h

@[simp]
theorem _root_.Fin.val_zModCast_of_pow {n d : ℕ} [NeZero d] [hnz : NeZero n] (a : Fin d) :
    (a.val : ZMod (d ^ n)).val = a :=
  a.val_zModCast_of_le (Nat.le_self_pow hnz.out d)

theorem _root_.Nat.val_zModCast_base_of_pow {n d : ℕ} [d.AtLeastTwo] [NeZero n] :
    (d : ZMod (d ^ (n + 1))).val = d := by
  apply val_natCast_of_lt
  apply lt_self_pow₀ <;> simp

example {n b e : ℕ} : (b ^ e).cast = (b.cast : ZMod n) ^ e := Nat.cast_pow b e

@[simp]
theorem val_cast_pow_eq_val_pow {n m d : ℕ} [d.AtLeastTwo] (hmn : m ≤ n) (i : Fin m) :
    (d ^ (i : ℕ) : ZMod (d ^ n)).val = d ^ (i : ℕ) := by
  rw [← Nat.cast_pow]
  exact val_natCast_of_lt (i.lt_pow_pow_self hmn)

-- name?
@[simp]
theorem lt_digit_mul {n m d : ℕ} [NeZero d] (hmn : m ≤ n) (i : Fin m) (x : Fin d) :
    x * d ^ (i : ℕ) < d ^ n := by
  refine lt_of_lt_of_le (b := d * d ^ (i : ℕ)) ?_ ?_
  · simp
  · rw [mul_comm, ← Nat.pow_succ]
    have : i < n := by grind
    simp [d.pow_le_pow_right, this]

@[simp]
theorem val_digit_mul {n m d : ℕ} [d.AtLeastTwo] [NeZero n] (hmn : m ≤ n) (i : Fin m) (x : Fin d) :
  (x * (d ^ (i : ℕ) : ZMod (d ^ n))).val = x.val * (d ^ (i : ℕ)) := by
    rw [val_mul_of_lt] <;> simp [hmn, x.val_zModCast_of_pow]

end trivialities

@[simp]
theorem val_expansion {n m d : ℕ} [d.AtLeastTwo] [NeZero n] (hmn : m ≤ n) (f : Fin m → Fin d) :
    (∑ i, f i * (d ^ (i : ℕ) : ZMod (d ^ n))).val = ∑ i, (f i).val * d ^ (i : ℕ) := by
  simp_rw [← val_digit_mul hmn]
  apply val_sum_of_lt
  simp [hmn, val_digit_mul]

theorem ofDigits_expansion {n d : ℕ} [NeZero d] (f : Fin n → Fin d) :
    f.ofDigits = ∑ i, f i * (d ^ (i : ℕ) : ZMod (d ^ n)) := by
  simp [ofDigits_def]

theorem digits_expansion {n d : ℕ} [NeZero d] (f : Fin n → Fin d) :
    (∑ i, (f i * (d ^ (i : ℕ)) : ZMod (d ^ n))).digits = f := by
  have := (congrArg digitsEquiv (ofDigits_expansion f)).symm
  rw [← digitsEquiv_apply, ← digitsEquiv_symm_apply] at *
  simp only [this, Equiv.apply_symm_apply]

theorem self_expansion {n d : ℕ} [NeZero d] (x : ZMod (d ^ n)) :
    x = ∑ i, x.digits i * (d ^ (i : ℕ) : ZMod (d ^ n)) := by
  conv_lhs => rw [show x = digitsEquiv.symm (digitsEquiv x) by simp]
  rw [digitsEquiv_symm_apply]
  simp only [ofDigits_expansion]
  rw [← digitsEquiv_apply]

-- Better than the simps theorem `_apply_val`.
theorem digitsEquiv_apply' {n d : ℕ} [hnz : NeZero d] (x : ZMod (d ^ n)) (i : Fin n) :
    x.digits i = ⟨(x.val / d ^ (i : ℕ)) % d, Nat.mod_lt _ ((Nat.pos_of_neZero d))⟩ := by
  ext
  simp [← digitsEquiv_apply, digitsEquiv_apply_val]

/-- Casting from `d ^ (n + 1)` to `d ^ n` removes the most significant digit -/
theorem digits_predHom {n d : ℕ} [NeZero d] (x : ZMod (d ^ (n + 1))) :
    (predHom d n x).digits = Fin.init x.digits := by
  conv_lhs => rw [self_expansion x]
  simp only [map_sum, map_mul]
  simp only [Fin.sum_univ_castSucc, Fin.val_last, predHom_ker']
  simp [-digitsEquiv_apply_val, digits_expansion, Fin.init_def]

theorem cast_pred {n d : ℕ} [NeZero d] (x : ZMod (d ^ (n + 1))) :
    (x.cast : ZMod (d ^ n))
      = ∑ i : Fin n, (x.digits i.castSucc) * (d ^ (i : ℕ) : ZMod (d ^ n)) := by
  conv_lhs => rw [self_expansion x.cast]
  rw [← predHom_apply, digits_predHom]
  simp [Fin.init_def]

/-- Casting down, then casting up clears the most significant digit -/
theorem cast_cast_pred {n d : ℕ} [NeZero n] [d.AtLeastTwo] (x : ZMod (d ^ (n + 1))) :
    (x.cast : ZMod (d ^ n)).cast
      = ∑ i : Fin n, (x.digits i.castSucc) * (d ^ (i : ℕ) : ZMod (d ^ (n + 1))) := by
  rw [cast_pred]
  apply val_injective
  rw [val_cast_succ_eq_val]
  rw [val_expansion (by simp), val_expansion (by simp)]

theorem mul_expansion {d n : ℕ} [NeZero n] [d.AtLeastTwo] (x : ZMod (d ^ (n + 1))) :
    (x * (d : ZMod (d ^ (n + 1)))) =
       ∑ i : Fin n, (x.digits i.castSucc) * (d ^ ((i : ℕ) + 1) : ZMod (d ^ (n + 1))) := by
  conv_lhs => rw [self_expansion x]
  rw [Finset.sum_mul]
  simp_rw [mul_assoc, ← pow_succ]
  simp only [Fin.sum_univ_castSucc, Fin.val_last]
  simp [-digitsEquiv_apply_val, natCast_pow_eq_zero_of_le]

theorem mul_eq_cast_cast_pred_mul {d n : ℕ} [NeZero n] [d.AtLeastTwo] (x : ZMod (d ^ (n + 1))) :
    (x * (d : ZMod (d ^ (n + 1)))) = (x.cast : ZMod (d ^ n)).cast * d := by
  rw [mul_expansion, cast_cast_pred, Finset.sum_mul]
  grind

---- not used
--/-- Casting from `d ^ n` to `d ^ (n + 1)` adds a digit with value 0 -/
--theorem digits_cast {n d : ℕ} [NeZero d] (x : ZMod (d ^ n)) :
--    (x.cast : ZMod (d ^ (n + 1))).digits = Fin.snoc (digitsEquiv x) 0 := by
--  ext i
--  simp only [digitsEquiv_apply', val_cast_succ_eq_val]
--  induction i using Fin.lastCases with
--  | last =>
--    have : x.val < d ^ n := by grind
--    simp [Nat.div_eq_zero_iff.mpr (Or.inr this)]
--  | cast i => simp
--
-- -- not used
-- /-- Casting from `d ^ (n + 1)` to `d ^ n` and back sets the most significant digit to 0 -/
-- theorem digits_predHom_cast {n d : ℕ} [NeZero d] (x : ZMod (d ^ (n + 1))) :
--     digitsEquiv ((predHom d n x).cast : ZMod (d ^ (n + 1)))
--       = Function.update x.digits (Fin.last n) 0 := by
--   simp only [digits_cast, digits_predHom]
--   ext i
--   induction i using Fin.lastCases with
--   | last => simp
--   | cast i => simp [Fin.init_def]


section BigEndian

/-- "Big endian" version -/
def digitsBEEquiv {n d : ℕ} [NeZero d] : (ZMod (d ^ n)) ≃ (Fin n → Fin d) :=
  digitsEquiv.trans (Equiv.arrowCongr Fin.revPerm (Equiv.refl (Fin d)))

-- TBD: API for converse
-- TBD: Think about how to introduce these functions

abbrev digitsBE {n d : ℕ} [NeZero d] (x : ZMod (d ^ n)) : (Fin n → Fin d) :=
  digitsBEEquiv x

abbrev _root_.Function.ofDigitsBE {n d : ℕ} [NeZero d] (f : Fin n → Fin d) : (ZMod (d ^ n)) :=
  digitsBEEquiv.symm f

-- TBD: Cleaner proof
theorem ofDigitsBE_apply {n d : ℕ} [NeZero d] (f : Fin n → Fin d) :
    f.ofDigitsBE = (fun i ↦ f i.rev).ofDigits := rfl

theorem digitsBE_symm_expansion {n d : ℕ} [NeZero d] (f : Fin n → Fin d) :
    f.ofDigitsBE = ∑ i : Fin n, (f i * d ^ (i.rev : ℕ) : ZMod (d ^ n)) := by
  simp only [ofDigitsBE_apply, ofDigits_expansion]
  rw [Finset.sum_equiv Fin.revPerm] <;> simp

-- Move up
variable {n d} (k x : Fin n → Fin d)

private theorem ofDigits_mul_ofDigitsBE_aux1 [NeZero d] :
    k.ofDigits * x.ofDigitsBE =
      ∑ i, ∑ j, (k i) * (x j) * (d ^ (i + j.rev : ℕ) : (ZMod (d ^ n))) := by
  simp only [ofDigits_expansion, digitsBE_symm_expansion, Fintype.sum_mul_sum]
  grind

private theorem ofDigitsLF_mul_ofDigitsMF_aux2 (j : Fin n) :
    ∑ i > j, ((k i) * (x j) * (d ^ (i + (j.rev : ℕ)) : ZMod (d ^ n))) = (0 : ZMod (d ^ n)) := by
  apply Finset.sum_eq_zero
  intro i hi
  rw [natCast_pow_eq_zero_of_le d] <;> grind

/-- Multiplication in `ZMod d ^ n` in terms of digits -/
theorem ofDigits_mul_ofDigitsBE [NeZero d] :
    k.ofDigits * x.ofDigitsBE =
      ∑ j, ∑ i ≤ j, (k i) * (x j) * (d ^ (i + (j.rev : ℕ)) : ZMod (d ^ n)) := by
  simp only [ofDigits_mul_ofDigitsBE_aux1]
  conv_lhs => rw [Finset.sum_comm]
  congr
  ext j
  simp only [Finset.sum_univ_split j, ofDigitsLF_mul_ofDigitsMF_aux2 k x j]
  simp

-- TBD: Unite these
theorem ofDigits_mul_ofDigitsBE_rec_aux1 [NeZero d] (k x : Fin (n + 1) → Fin d) :
    k.ofDigits * x.ofDigitsBE =
      (∑ j : Fin n, ∑ i ≤ j, ↑((k i.castSucc) * (x j.castSucc) * (d ^ (i + (j.rev : ℕ) + 1))))
      + (∑ i : Fin (n + 1), ↑((k i) * (x (Fin.last n)) * d ^ (i : ℕ))) := by
  conv_lhs => simp only [ofDigits_mul_ofDigitsBE, Fin.sum_univ_castSucc, Fin.sum_Iic_castSucc]
  congr <;> grind
--
theorem ofDigits_mul_ofDigitsBE_rec_aux2 [NeZero d] (k x : Fin (n + 1) → Fin d) :
    k.ofDigits * x.ofDigitsBE =
      (∑ j : Fin n, ∑ i ≤ j, (k i.castSucc) * (x j.castSucc) *
        ((d ^ (i + (j.rev : ℕ)) : ZMod (d ^ (n + 1))))) * d
          + (∑ i : Fin (n + 1), (k i) * (x (Fin.last n)) * (d ^ (i : ℕ) : ZMod (d ^ (n + 1)))) := by
  simp_rw [ofDigits_mul_ofDigitsBE_rec_aux1, Finset.sum_mul]
  grind

/-- A recursive formula for multiplication in `ZMod d ^ n` in terms of digits -/
theorem ofDigits_mul_ofDigitsBE_rec [d.AtLeastTwo] [NeZero n] (k x : Fin (n + 1) → Fin d) :
    k.ofDigits * x.ofDigitsBE =
      ((Fin.init k).ofDigits * (Fin.init x).ofDigitsBE).cast * d
        + (∑ i : Fin (n + 1), k i * x (Fin.last n) * (d ^ (i : ℕ) : ZMod (d ^ (n + 1)))) := by
  rw [ofDigits_mul_ofDigitsBE_rec_aux2, mul_eq_cast_cast_pred_mul]
  simp only [← castHom_apply, pow_div_pow_succ, map_sum, map_mul]
  simp [ofDigits_mul_ofDigitsBE, Fin.init_def]

end BigEndian

-- This should go into QFT.lean

/-- A character of order `d ^ n.succ` evaluated at `x * d` equals the character
of order `d ^ n` evaluated at x. -/
theorem stdAddChar_cast {d n : ℕ} [NeZero d] (x : ZMod (d ^ n)) :
    stdAddChar (x.cast * d : ZMod (d ^ (n + 1))) = stdAddChar x := by
  conv_rhs => rw [← natCast_zmod_val x]
  simp_rw [cast_eq_val, ← Nat.cast_mul, stdAddChar_apply, toCircle_natCast, pow_add]
  push_cast
  field_simp [NeZero.ne _]

theorem idftRec {n d : ℕ} [d.AtLeastTwo] [NeZero n] (k x : Fin (n + 1) → Fin d) :
  stdAddChar (k.ofDigits * x.ofDigitsBE) =
    stdAddChar ((Fin.init k).ofDigits * (Fin.init x).ofDigitsBE) *
      stdAddChar (∑ i, k i * x (Fin.last n) * (d ^ (i : ℕ)) : ZMod (d ^ (n + 1))) := by
  rw [ofDigits_mul_ofDigitsBE_rec, AddChar.map_add_eq_mul, stdAddChar_cast]


end ZMod
